### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [nmsmith22389/codepen-dracula#1]
Hello @nmsmith22389!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way (I love Codepen)!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by nmsmith22389** [comment]
Well thanks for noticing! I was actually planning on submitting it after it was finished but now is as good a time as any! I also have uncommitted changes that update almost the whole site as well as the JSON for the Codepen Enhancement Suite chrome extension to add the syntax highlighting. I'll start committing all the changes if you want to transfer it over. Thanks!

PS
I also have a 90% finished theme for Telegram that will be submitted to their theme store after testing if you are interested in that as well. I can start pushing to the master on there as well. Here are some screen shots and the repo.

https://github.com/nmsmith22389/dracula-telegram

![telegram](https://cloud.githubusercontent.com/assets/8648114/23593258/0552f6b8-01d2-11e7-83e2-20411b596804.png)
![telegram 1](https://cloud.githubusercontent.com/assets/8648114/23593257/05522a62-01d2-11e7-8c21-c48e018cb32a.png)
![telegram 2](https://cloud.githubusercontent.com/assets/8648114/23593259/0553bd96-01d2-11e7-9ce6-24392383d59d.png)

**Comment by zenorocha** [comment]
That's awesome! I'm looking forward to use this theme on Codepen.

I sent you an invitation to the GitHub organization, let me know when you accept it.

About the telegram theme, it looks great too! The only problem is that I'm also reaching out to @mazipan, which is the owner of https://github.com/mazipan/dracula-telegram-theme. I was thinking about making his the official repo, but based on these screenshots your theme looks more accurate to the color scheme. 

Any thoughts on how you two can collaborate? Maybe transfer https://github.com/nmsmith22389/dracula-telegram to the Dracula org and add both of you as contributors?

**Comment by mazipan** [comment]
I just transferred my repo to Dracula.
I always open to any corrections, so just PR to make the repo better and looks more "Dracula".
Hope you can join to contribute @nmsmith22389

**Comment by mazipan** [comment]
Just added @nmsmith22389 as a member of repo.
Can't wait your contribution. 👍

**Comment by nmsmith22389** [comment]
I don't mind merging ours so I'll just PR whenever I get the chance. Thanks!

**Comment by mazipan** [comment]
Very thankful 
Honestly I have no much time to maintain this repo 
So your help will so appreciated.

**Comment by zenorocha** [comment]
Hey @mazipan, if you don't have time to maintain then I prefer @nmsmith22389 to transfer his repo. I'll still add you as maintainer but at least we'll have something more up to date.

@nmsmith22389, can you transfer both of your repos?

**Comment by nmsmith22389** [comment]
Yeah! I'll get working on getting them over. Is there anything I need to know or keep in mind for doing it?

**Comment by zenorocha** [comment]
I don't think so, the only thing is following this template 👉 https://github.com/dracula/template

**Comment by zenorocha** [comment]
Friendly ping ;) Any updates on this one @nmsmith22389?

**Comment by nmsmith22389** [comment]
Sorry! I have been very busy on other projects. The Telegram one should already be moved over and everything but the CodePen project was never finished and I'm not sure if I have to time right now to finish it. Let me know if you want to just wait for me to finish it or just or if I should move it anyways or if you would like someone else to take it over.
